// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameCommon.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserInfo struct {
	Uid              *int32  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Male             *int32  `protobuf:"varint,3,opt,name=male" json:"male,omitempty"`
	Exp              *int32  `protobuf:"varint,4,opt,name=exp" json:"exp,omitempty"`
	Coin             *int32  `protobuf:"varint,5,opt,name=coin" json:"coin,omitempty"`
	Dimond           *int32  `protobuf:"varint,6,opt,name=dimond" json:"dimond,omitempty"`
	Level            *int32  `protobuf:"varint,7,opt,name=level" json:"level,omitempty"`
	StrInfo          *string `protobuf:"bytes,8,opt,name=strInfo" json:"strInfo,omitempty"`
	IsRobot          *bool   `protobuf:"varint,9,opt,name=isRobot,def=0" json:"isRobot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

const Default_UserInfo_IsRobot bool = false

func (m *UserInfo) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserInfo) GetMale() int32 {
	if m != nil && m.Male != nil {
		return *m.Male
	}
	return 0
}

func (m *UserInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *UserInfo) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *UserInfo) GetDimond() int32 {
	if m != nil && m.Dimond != nil {
		return *m.Dimond
	}
	return 0
}

func (m *UserInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *UserInfo) GetStrInfo() string {
	if m != nil && m.StrInfo != nil {
		return *m.StrInfo
	}
	return ""
}

func (m *UserInfo) GetIsRobot() bool {
	if m != nil && m.IsRobot != nil {
		return *m.IsRobot
	}
	return Default_UserInfo_IsRobot
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "UserInfo")
}

func init() { proto.RegisterFile("gameCommon.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x3d, 0x8a, 0xc3, 0x30,
	0x10, 0x85, 0xd1, 0xda, 0xf2, 0xcf, 0x54, 0x46, 0x2c, 0xcb, 0x74, 0x6b, 0xb6, 0x72, 0xb5, 0x07,
	0xd8, 0x76, 0xab, 0xb4, 0x82, 0x1c, 0x40, 0x89, 0xc7, 0x41, 0x20, 0x69, 0x8c, 0xe5, 0x04, 0xdf,
	0x33, 0x17, 0x0a, 0x92, 0xe3, 0xee, 0x7b, 0x1f, 0xef, 0x31, 0x03, 0xdd, 0xcd, 0x78, 0xfa, 0x67,
	0xef, 0x39, 0xfc, 0xce, 0x0b, 0xaf, 0xfc, 0xf3, 0x14, 0xd0, 0x9c, 0x23, 0x2d, 0xa7, 0x30, 0xb1,
	0xea, 0xa0, 0xb8, 0xdb, 0x11, 0x45, 0x2f, 0x06, 0xa9, 0x13, 0x2a, 0x05, 0x65, 0x30, 0x9e, 0xf0,
	0xa3, 0x17, 0x43, 0xab, 0x33, 0x27, 0xe7, 0x8d, 0x23, 0x2c, 0x72, 0x2d, 0x73, 0x5a, 0xd2, 0x36,
	0x63, 0xb9, 0x2f, 0x69, 0x9b, 0x53, 0xeb, 0xca, 0x36, 0xa0, 0xdc, 0x5b, 0x89, 0xd5, 0x17, 0x54,
	0xa3, 0xf5, 0x1c, 0x46, 0xac, 0xb2, 0x7d, 0x27, 0xf5, 0x09, 0xd2, 0xd1, 0x83, 0x1c, 0xd6, 0x59,
	0xef, 0x41, 0x21, 0xd4, 0x71, 0xcd, 0x8f, 0x61, 0x93, 0xcf, 0x1f, 0x51, 0x7d, 0x43, 0x6d, 0xa3,
	0xe6, 0x0b, 0xaf, 0xd8, 0xf6, 0x62, 0x68, 0xfe, 0xe4, 0x64, 0x5c, 0x24, 0x7d, 0xd8, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0xca, 0x74, 0xdd, 0xe8, 0x00, 0x00, 0x00,
}
