// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameS2C.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ErrorCode int32

const (
	ErrorCode_LoginErrInvalidAccount ErrorCode = 1
	ErrorCode_LoginErrAlreadyLogined ErrorCode = 2
	ErrorCode_CreateDeskErrLackMoney ErrorCode = 3
	ErrorCode_CreateDeskErrNotLogin  ErrorCode = 4
)

var ErrorCode_name = map[int32]string{
	1: "LoginErrInvalidAccount",
	2: "LoginErrAlreadyLogined",
	3: "CreateDeskErrLackMoney",
	4: "CreateDeskErrNotLogin",
}
var ErrorCode_value = map[string]int32{
	"LoginErrInvalidAccount": 1,
	"LoginErrAlreadyLogined": 2,
	"CreateDeskErrLackMoney": 3,
	"CreateDeskErrNotLogin":  4,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

// 登陆返回数据
type LoginRsp struct {
	Ret              *int32    `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Info             *UserInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *LoginRsp) Reset()                    { *m = LoginRsp{} }
func (m *LoginRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()               {}
func (*LoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *LoginRsp) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *LoginRsp) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 创建房间返回数据
type CreateDeskRsp struct {
	Ret              *int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	DeskId           *int32 `protobuf:"varint,2,opt,name=desk_id,json=deskId" json:"desk_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateDeskRsp) Reset()                    { *m = CreateDeskRsp{} }
func (m *CreateDeskRsp) String() string            { return proto.CompactTextString(m) }
func (*CreateDeskRsp) ProtoMessage()               {}
func (*CreateDeskRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CreateDeskRsp) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *CreateDeskRsp) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

// 进房间桌子
type EnterDeskRep struct {
	Ret              *int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	DeskId           *int32 `protobuf:"varint,2,opt,name=desk_id,json=deskId" json:"desk_id,omitempty"`
	Seat             *int32 `protobuf:"varint,3,opt,name=seat" json:"seat,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EnterDeskRep) Reset()                    { *m = EnterDeskRep{} }
func (m *EnterDeskRep) String() string            { return proto.CompactTextString(m) }
func (*EnterDeskRep) ProtoMessage()               {}
func (*EnterDeskRep) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *EnterDeskRep) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *EnterDeskRep) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func (m *EnterDeskRep) GetSeat() int32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

// 桌子玩家信息
type DeskPlayerInfo struct {
	Info             *UserInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Ip               *string   `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *DeskPlayerInfo) Reset()                    { *m = DeskPlayerInfo{} }
func (m *DeskPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*DeskPlayerInfo) ProtoMessage()               {}
func (*DeskPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *DeskPlayerInfo) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DeskPlayerInfo) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

type DeskPlayerInfoList struct {
	Players          []*DeskPlayerInfo `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DeskPlayerInfoList) Reset()                    { *m = DeskPlayerInfoList{} }
func (m *DeskPlayerInfoList) String() string            { return proto.CompactTextString(m) }
func (*DeskPlayerInfoList) ProtoMessage()               {}
func (*DeskPlayerInfoList) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *DeskPlayerInfoList) GetPlayers() []*DeskPlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRsp)(nil), "LoginRsp")
	proto.RegisterType((*CreateDeskRsp)(nil), "CreateDeskRsp")
	proto.RegisterType((*EnterDeskRep)(nil), "EnterDeskRep")
	proto.RegisterType((*DeskPlayerInfo)(nil), "DeskPlayerInfo")
	proto.RegisterType((*DeskPlayerInfoList)(nil), "DeskPlayerInfoList")
	proto.RegisterEnum("ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("gameS2C.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x4f, 0x6b, 0xc2, 0x40,
	0x10, 0xc5, 0x49, 0xa2, 0xb5, 0x8e, 0xd5, 0x86, 0x85, 0xb6, 0xa9, 0x50, 0x90, 0x9c, 0x6c, 0x0f,
	0x1e, 0x3c, 0xb6, 0x07, 0x91, 0x34, 0x07, 0x41, 0x4b, 0x49, 0xe9, 0xb9, 0x2c, 0xee, 0x28, 0x8b,
	0xba, 0x13, 0x66, 0xb7, 0x05, 0xfb, 0xe9, 0x4b, 0x56, 0xfa, 0x27, 0xe0, 0xa5, 0xb7, 0x7d, 0xef,
	0xed, 0xfb, 0xf1, 0x18, 0xe8, 0xae, 0xe5, 0x0e, 0x5f, 0xc6, 0xd9, 0xa8, 0x64, 0x72, 0xd4, 0x8f,
	0x2b, 0x99, 0xd1, 0x6e, 0x47, 0xe6, 0xe0, 0xa4, 0x0f, 0x70, 0x3a, 0xa7, 0xb5, 0x36, 0x85, 0x2d,
	0x45, 0x0c, 0x11, 0xa3, 0x4b, 0x82, 0x41, 0x30, 0x6c, 0x16, 0xd5, 0x53, 0xdc, 0x40, 0x43, 0x9b,
	0x15, 0x25, 0xe1, 0x20, 0x18, 0x76, 0xc6, 0xed, 0xd1, 0xab, 0x45, 0x9e, 0x99, 0x15, 0x15, 0xde,
	0x4e, 0xef, 0xa1, 0x9b, 0x31, 0x4a, 0x87, 0x8f, 0x68, 0x37, 0xc7, 0x09, 0x57, 0xd0, 0x52, 0x68,
	0x37, 0x6f, 0x5a, 0x79, 0x48, 0xb3, 0x38, 0xa9, 0xe4, 0x4c, 0xa5, 0x0b, 0x38, 0xcb, 0x8d, 0x43,
	0xf6, 0x55, 0xfc, 0x4f, 0x55, 0x08, 0x68, 0x58, 0x94, 0x2e, 0x89, 0xbc, 0xeb, 0xdf, 0xe9, 0x04,
	0x7a, 0x15, 0xe9, 0x79, 0x2b, 0xf7, 0x87, 0x89, 0x3f, 0xdb, 0x83, 0xa3, 0xdb, 0x45, 0x0f, 0x42,
	0x5d, 0x7a, 0x70, 0xbb, 0x08, 0x75, 0x99, 0x4e, 0x40, 0xd4, 0x01, 0x73, 0x6d, 0x9d, 0xb8, 0x85,
	0x56, 0xe9, 0x1d, 0x9b, 0x04, 0x83, 0x68, 0xd8, 0x19, 0x9f, 0x8f, 0xea, 0xbf, 0x8a, 0xef, 0xfc,
	0xee, 0x13, 0xda, 0x39, 0x33, 0x71, 0x46, 0x0a, 0x45, 0x1f, 0x2e, 0xfd, 0x59, 0x73, 0xe6, 0x99,
	0xf9, 0x90, 0x5b, 0xad, 0xa6, 0xcb, 0x25, 0xbd, 0x1b, 0x17, 0x07, 0x7f, 0xb3, 0xe9, 0x96, 0x51,
	0xaa, 0xbd, 0x97, 0xa8, 0xe2, 0xb0, 0xca, 0x7e, 0x2f, 0x9a, 0x33, 0xcf, 0xe5, 0x72, 0xb3, 0x20,
	0x83, 0xfb, 0x38, 0x12, 0xd7, 0x70, 0x51, 0xcb, 0x9e, 0xc8, 0xf9, 0x62, 0xdc, 0xf8, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x84, 0x0d, 0xa3, 0xcc, 0xe7, 0x01, 0x00, 0x00,
}
