// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameC2S.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	gameC2S.proto
	gameCommon.proto
	gameS2C.proto
	ProtoDefine.proto

It has these top-level messages:
	LoginReq
	EnterDeskReq
	UserInfo
	LoginRsp
	CreateDeskRsp
	EnterDeskRep
	DeskPlayerInfo
	DeskPlayerInfoList
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginReq struct {
	Uid              *int32  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Guid             *string `protobuf:"bytes,2,opt,name=guid" json:"guid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginReq) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *LoginReq) GetGuid() string {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return ""
}

type EnterDeskReq struct {
	DeskId           *int32 `protobuf:"varint,1,opt,name=desk_id,json=deskId" json:"desk_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EnterDeskReq) Reset()                    { *m = EnterDeskReq{} }
func (m *EnterDeskReq) String() string            { return proto.CompactTextString(m) }
func (*EnterDeskReq) ProtoMessage()               {}
func (*EnterDeskReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EnterDeskReq) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "LoginReq")
	proto.RegisterType((*EnterDeskReq)(nil), "EnterDeskReq")
}

func init() { proto.RegisterFile("gameC2S.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0xcc, 0x4d,
	0x75, 0x36, 0x0a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe0, 0xe2, 0xf0, 0xc9, 0x4f,
	0xcf, 0xcc, 0x0b, 0x4a, 0x2d, 0x14, 0x12, 0xe0, 0x62, 0x2e, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0d, 0x02, 0x31, 0x85, 0x84, 0xb8, 0x58, 0xd2, 0x41, 0x42, 0x4c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x60, 0xb6, 0x92, 0x3a, 0x17, 0x8f, 0x6b, 0x5e, 0x49, 0x6a, 0x91, 0x4b, 0x6a, 0x71,
	0x36, 0x48, 0x97, 0x38, 0x17, 0x7b, 0x4a, 0x6a, 0x71, 0x76, 0x3c, 0x5c, 0x27, 0x1b, 0x88, 0xeb,
	0x99, 0x02, 0x08, 0x00, 0x00, 0xff, 0xff, 0x17, 0x27, 0x6a, 0xb4, 0x6a, 0x00, 0x00, 0x00,
}
