// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ProtoDefine.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C2S_ProtoId int32

const (
	C2S_ProtoId_cLogin      C2S_ProtoId = 193
	C2S_ProtoId_cHeartBeat  C2S_ProtoId = 194
	C2S_ProtoId_cCreateDesk C2S_ProtoId = 195
)

var C2S_ProtoId_name = map[int32]string{
	193: "cLogin",
	194: "cHeartBeat",
	195: "cCreateDesk",
}
var C2S_ProtoId_value = map[string]int32{
	"cLogin":      193,
	"cHeartBeat":  194,
	"cCreateDesk": 195,
}

func (x C2S_ProtoId) Enum() *C2S_ProtoId {
	p := new(C2S_ProtoId)
	*p = x
	return p
}
func (x C2S_ProtoId) String() string {
	return proto.EnumName(C2S_ProtoId_name, int32(x))
}
func (x *C2S_ProtoId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(C2S_ProtoId_value, data, "C2S_ProtoId")
	if err != nil {
		return err
	}
	*x = C2S_ProtoId(value)
	return nil
}
func (C2S_ProtoId) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type S2C_ProtoId int32

const (
	S2C_ProtoId_sLogin      S2C_ProtoId = 161
	S2C_ProtoId_sHeartBeat  S2C_ProtoId = 162
	S2C_ProtoId_sCreateDesk S2C_ProtoId = 163
)

var S2C_ProtoId_name = map[int32]string{
	161: "sLogin",
	162: "sHeartBeat",
	163: "sCreateDesk",
}
var S2C_ProtoId_value = map[string]int32{
	"sLogin":      161,
	"sHeartBeat":  162,
	"sCreateDesk": 163,
}

func (x S2C_ProtoId) Enum() *S2C_ProtoId {
	p := new(S2C_ProtoId)
	*p = x
	return p
}
func (x S2C_ProtoId) String() string {
	return proto.EnumName(S2C_ProtoId_name, int32(x))
}
func (x *S2C_ProtoId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(S2C_ProtoId_value, data, "S2C_ProtoId")
	if err != nil {
		return err
	}
	*x = S2C_ProtoId(value)
	return nil
}
func (S2C_ProtoId) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func init() {
	proto.RegisterEnum("C2S_ProtoId", C2S_ProtoId_name, C2S_ProtoId_value)
	proto.RegisterEnum("S2C_ProtoId", S2C_ProtoId_name, S2C_ProtoId_value)
}

func init() { proto.RegisterFile("ProtoDefine.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0c, 0x28, 0xca, 0x2f,
	0xc9, 0x77, 0x49, 0x4d, 0xcb, 0xcc, 0x4b, 0xd5, 0x2b, 0x00, 0xb1, 0xb5, 0x6c, 0xb9, 0xb8, 0x9d,
	0x8d, 0x82, 0xe3, 0xc1, 0x12, 0x9e, 0x29, 0x42, 0xdc, 0x5c, 0x6c, 0xc9, 0x3e, 0xf9, 0xe9, 0x99,
	0x79, 0x02, 0x07, 0x19, 0x85, 0xf8, 0xb9, 0xb8, 0x92, 0x3d, 0x52, 0x13, 0x8b, 0x4a, 0x9c, 0x52,
	0x13, 0x4b, 0x04, 0x0e, 0x31, 0x0a, 0x09, 0x70, 0x71, 0x27, 0x3b, 0x17, 0xa5, 0x26, 0x96, 0xa4,
	0xba, 0xa4, 0x16, 0x67, 0x0b, 0x1c, 0x66, 0x04, 0x69, 0x0f, 0x36, 0x72, 0x46, 0xd6, 0x5e, 0x0c,
	0xd1, 0xbe, 0x10, 0xac, 0xbd, 0x18, 0xa1, 0x7d, 0x11, 0x58, 0x7b, 0x31, 0x92, 0xf6, 0xc5, 0x8c,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xcc, 0xc6, 0x4d, 0x91, 0x00, 0x00, 0x00,
}
